const ActionTypes = {
  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  GET_CART_ITEMS_REQUEST: "GET_CART_ITEMS_REQUEST",
  GET_CART_ITEMS_SUCCESS: "GET_CART_ITEMS_SUCCESS",
  GET_CART_ITEMS_FAILURE: "GET_CART_ITEMS_FAILURE",

  ADD_ITEM_TO_CART_REQUEST: "ADD_ITEM_TO_CART_REQUEST",
  ADD_ITEM_TO_CART_SUCCESS: "ADD_ITEM_TO_CART_SUCCESS",
  ADD_ITEM_TO_CART_FAILURE: "ADD_ITEM_TO_CART_FAILURE",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",

  REDUCE_CART_ITEM_REQUEST: "REDUCE_CART_ITEM_REQUEST",
  REDUCE_CART_ITEM_SUCCESS: "REDUCE_CART_ITEM_SUCCESS",
  REDUCE_CART_ITEM_FAILURE: "REDUCE_CART_ITEM_FAILURE",

  UPDATE_CART_ITEM_REQUEST: "UPDATE_CART_ITEM_REQUEST",
  UPDATE_CART_ITEM_SUCCESS: "UPDATE_CART_ITEM_SUCCESS",
  UPDATE_CART_ITEM_FAILURE: "UPDATE_CART_ITEM_FAILURE",
};

export default ActionTypes;
