const ActionTypes = {
  FIND_PRODUCT_BY_ID_REQUEST: "FIND_PRODUCT_BY_ID_REQUEST",
  FIND_PRODUCT_BY_ID_SUCCESS: "FIND_PRODUCT_BY_ID_SUCCESS",
  FIND_PRODUCT_BY_ID_FAILURE: "FIND_PRODUCT_BY_ID_FAILURE",

  FIND_PRODUCTS_REQUEST: "FIND_PRODUCTS_REQUEST",
  FIND_PRODUCTS_SUCCESS: "FIND_PRODUCTS_SUCCESS",
  FIND_PRODUCTS_FAILURE: "FIND_PRODUCTS_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
};

export default ActionTypes;
