const ActionTypes = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  FIND_PRODUCT_BY_ID_REQUEST: "FIND_PRODUCT_BY_ID_REQUEST",
  FIND_PRODUCT_BY_ID_SUCCESS: "FIND_PRODUCT_BY_ID_SUCCESS",
  FIND_PRODUCT_BY_ID_FAILURE: "FIND_PRODUCT_BY_ID_FAILURE",

  FIND_PRODUCTS_REQUEST: "FIND_PRODUCTS_REQUEST",
  FIND_PRODUCTS_SUCCESS: "FIND_PRODUCTS_SUCCESS",
  FIND_PRODUCTS_FAILURE: "FIND_PRODUCTS_FAILURE",

  GET_TOP_LEVEL_CATEGORIES_REQUEST: "GET_TOP_LEVEL_CATEGORIES_REQUEST",
  GET_TOP_LEVEL_CATEGORIES_SUCCESS: "GET_TOP_LEVEL_CATEGORIES_SUCCESS",
  GET_TOP_LEVEL_CATEGORIES_FAILURE: "GET_TOP_LEVEL_CATEGORIES_FAILURE",

  GET_SECOND_LEVEL_CATEGORIES_REQUEST: "GET_SECOND_LEVEL_CATEGORIES_REQUEST",
  GET_SECOND_LEVEL_CATEGORIES_SUCCESS: "GET_SECOND_LEVEL_CATEGORIES_SUCCESS",
  GET_SECOND_LEVEL_CATEGORIES_FAILURE: "GET_SECOND_LEVEL_CATEGORIES_FAILURE",

  GET_THIRD_LEVEL_CATEGORIES_REQUEST: "GET_THIRD_LEVEL_CATEGORIES_REQUEST",
  GET_THIRD_LEVEL_CATEGORIES_SUCCESS: "GET_THIRD_LEVEL_CATEGORIES_SUCCESS",
  GET_THIRD_LEVEL_CATEGORIES_FAILURE: "GET_THIRD_LEVEL_CATEGORIES_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

  UPLOAD_IMAGE_REQUEST: "UPLOAD_IMAGE_REQUEST",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILURE: "UPLOAD_IMAGE_FAILURE",
};

export default ActionTypes;
