const ActionTypes = {
  GET_PRODUCTS_CAROUSEL_REQUEST: "GET_PRODUCTS_CAROUSEL_REQUEST",
  GET_PRODUCTS_CAROUSEL_SUCCESS: "GET_PRODUCTS_CAROUSEL_SUCCESS",
  GET_PRODUCTS_CAROUSEL_FAILURE: "GET_PRODUCTS_CAROUSEL_FAILURE",

  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  FIND_PRODUCT_BY_ID_REQUEST: "FIND_PRODUCT_BY_ID_REQUEST",
  FIND_PRODUCT_BY_ID_SUCCESS: "FIND_PRODUCT_BY_ID_SUCCESS",
  FIND_PRODUCT_BY_ID_FAILURE: "FIND_PRODUCT_BY_ID_FAILURE",

  FIND_PRODUCTS_REQUEST: "FIND_PRODUCTS_REQUEST",
  FIND_PRODUCTS_SUCCESS: "FIND_PRODUCTS_SUCCESS",
  FIND_PRODUCTS_FAILURE: "FIND_PRODUCTS_FAILURE",

  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",

  GET_TOP_LEVEL_CATEGORIES_REQUEST: "GET_TOP_LEVEL_CATEGORIES_REQUEST",
  GET_TOP_LEVEL_CATEGORIES_SUCCESS: "GET_TOP_LEVEL_CATEGORIES_SUCCESS",
  GET_TOP_LEVEL_CATEGORIES_FAILURE: "GET_TOP_LEVEL_CATEGORIES_FAILURE",

  ADD_TOP_LEVEL_CATEGORIES_REQUEST: "ADD_TOP_LEVEL_CATEGORIES_REQUEST",
  ADD_TOP_LEVEL_CATEGORIES_SUCCESS: "ADD_TOP_LEVEL_CATEGORIES_SUCCESS",
  ADD_TOP_LEVEL_CATEGORIES_FAILURE: "ADD_TOP_LEVEL_CATEGORIES_FAILURE",

  DELETE_TOP_LEVEL_CATEGORIES_REQUEST: "DELETE_TOP_LEVEL_CATEGORIES_REQUEST",
  DELETE_TOP_LEVEL_CATEGORIES_SUCCESS: "DELETE_TOP_LEVEL_CATEGORIES_SUCCESS",
  DELETE_TOP_LEVEL_CATEGORIES_FAILURE: "DELETE_TOP_LEVEL_CATEGORIES_FAILURE",

  GET_SECOND_LEVEL_CATEGORIES_REQUEST: "GET_SECOND_LEVEL_CATEGORIES_REQUEST",
  GET_SECOND_LEVEL_CATEGORIES_SUCCESS: "GET_SECOND_LEVEL_CATEGORIES_SUCCESS",
  GET_SECOND_LEVEL_CATEGORIES_FAILURE: "GET_SECOND_LEVEL_CATEGORIES_FAILURE",

  ADD_SECOND_LEVEL_CATEGORIES_REQUEST: "ADD_SECOND_LEVEL_CATEGORIES_REQUEST",
  ADD_SECOND_LEVEL_CATEGORIES_SUCCESS: "ADD_SECOND_LEVEL_CATEGORIES_SUCCESS",
  ADD_SECOND_LEVEL_CATEGORIES_FAILURE: "ADD_SECOND_LEVEL_CATEGORIES_FAILURE",

  DELETE_SECOND_LEVEL_CATEGORIES_REQUEST:
    "DELETE_SECOND_LEVEL_CATEGORIES_REQUEST",
  DELETE_SECOND_LEVEL_CATEGORIES_SUCCESS:
    "DELETE_SECOND_LEVEL_CATEGORIES_SUCCESS",
  DELETE_SECOND_LEVEL_CATEGORIES_FAILURE:
    "DELETE_SECOND_LEVEL_CATEGORIES_FAILURE",

  GET_THIRD_LEVEL_CATEGORIES_REQUEST: "GET_THIRD_LEVEL_CATEGORIES_REQUEST",
  GET_THIRD_LEVEL_CATEGORIES_SUCCESS: "GET_THIRD_LEVEL_CATEGORIES_SUCCESS",
  GET_THIRD_LEVEL_CATEGORIES_FAILURE: "GET_THIRD_LEVEL_CATEGORIES_FAILURE",

  ADD_THIRD_LEVEL_CATEGORIES_REQUEST: "ADD_THIRD_LEVEL_CATEGORIES_REQUEST",
  ADD_THIRD_LEVEL_CATEGORIES_SUCCESS: "ADD_THIRD_LEVEL_CATEGORIES_SUCCESS",
  ADD_THIRD_LEVEL_CATEGORIES_FAILURE: "ADD_THIRD_LEVEL_CATEGORIES_FAILURE",

  DELETE_THIRD_LEVEL_CATEGORIES_REQUEST:
    "DELETE_THIRD_LEVEL_CATEGORIES_REQUEST",
  DELETE_THIRD_LEVEL_CATEGORIES_SUCCESS:
    "DELETE_THIRD_LEVEL_CATEGORIES_SUCCESS",
  DELETE_THIRD_LEVEL_CATEGORIES_FAILURE:
    "DELETE_THIRD_LEVEL_CATEGORIES_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  EDIT_PRODUCT_REQUEST: "EDIT_PRODUCT_REQUEST",
  EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
  EDIT_PRODUCT_FAILURE: "EDIT_PRODUCT_FAILURE",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",

  UPLOAD_IMAGE_REQUEST: "UPLOAD_IMAGE_REQUEST",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILURE: "UPLOAD_IMAGE_FAILURE",
};

export default ActionTypes;
