const ActionTypes = {
  FIND_PRODUCT_BY_ID_REQUEST: "FIND_PRODUCT_BY_ID_REQUEST",
  FIND_PRODUCT_BY_ID_SUCCESS: "FIND_PRODUCT_BY_ID_SUCCESS",
  FIND_PRODUCT_BY_ID_FAILURE: "FIND_PRODUCT_BY_ID_FAILURE",

  FIND_PRODUCTS_REQUEST: "FIND_PRODUCTS_REQUEST",
  FIND_PRODUCTS_SUCCESS: "FIND_PRODUCTS_SUCCESS",
  FIND_PRODUCTS_FAILURE: "FIND_PRODUCTS_FAILURE",
};

export default ActionTypes;
