const ActionTypes = {
  GET_ADDRESSES_REQUEST: "GET_ADDRESSES_REQUEST",
  GET_ADDRESSES_SUCCESS: "GET_ADDRESSES_SUCCESS",
  GET_ADDRESSES_FAILURE: "GET_ADDRESSES_FAILURE",

  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",

  SET_ACTIVE_ADDRESS_REQUEST: "SET_ACTIVE_ADDRESS_REQUEST",
  SET_ACTIVE_ADDRESS_SUCCESS: "SET_ACTIVE_ADDRESS_SUCCESS",
  SET_ACTIVE_ADDRESS_FAILURE: "SET_ACTIVE_ADDRESS_FAILURE",

  GET_ACTIVE_ADDRESS_REQUEST: "GET_ACTIVE_ADDRESS_REQUEST",
  GET_ACTIVE_ADDRESS_SUCCESS: "GET_ACTIVE_ADDRESS_SUCCESS",
  GET_ACTIVE_ADDRESS_FAILURE: "GET_ACTIVE_ADDRESS_FAILURE",

  GET_ADDRESS_BY_ID_REQUEST: "GET_ADDRESS_BY_ID_REQUEST",
  GET_ADDRESS_BY_ID_SUCCESS: "GET_ADDRESS_BY_ID_SUCCESS",
  GET_ADDRESS_BY_ID_FAILURE: "GET_ADDRESS_BY_ID_FAILURE",

  REMOVE_ADDRESS_REQUEST: "REMOVE_ADDRESS_REQUEST",
  REMOVE_ADDRESS_SUCCESS: "REMOVE_ADDRESS_SUCCESS",
  REMOVE_ADDRESS_FAILURE: "REMOVE_ADDRESS_FAILURE",

  UPDATE_ADDRESS_REQUEST: "UPDATE_ADDRESS_REQUEST",
  UPDATE_ADDRESS_SUCCESS: "UPDATE_ADDRESS_SUCCESS",
  UPDATE_ADDRESS_FAILURE: "UPDATE_ADDRESS_FAILURE",
};

export default ActionTypes;
