const ActionTypes = {
  GET_WISHLIST_REQUEST: "GET_WISHLIST_REQUEST",
  GET_WISHLIST_SUCCESS: "GET_WISHLIST_SUCCESS",
  GET_WISHLIST_FAILURE: "GET_WISHLIST_FAILURE",

  ADD_ITEM_TO_WISHLIST_REQUEST: "ADD_ITEM_TO_WISHLIST_REQUEST",
  ADD_ITEM_TO_WISHLIST_SUCCESS: "ADD_ITEM_TO_WISHLIST_SUCCESS",
  ADD_ITEM_TO_WISHLIST_FAILURE: "ADD_ITEM_TO_WISHLIST_FAILURE",

  REMOVE_ITEM_FROM_WISHLIST_REQUEST: "REMOVE_ITEM_FROM_WISHLIST_REQUEST",
  REMOVE_ITEM_FROM_WISHLIST_SUCCESS: "REMOVE_ITEM_FROM_WISHLIST_SUCCESS",
  REMOVE_ITEM_FROM_WISHLIST_FAILURE: "REMOVE_ITEM_FROM_WISHLIST_FAILURE",
};

export default ActionTypes;
