const cameras = [
  {
    id: 109,
    title: "Monopod",
    description:
      "The Monopod is a versatile camera accessory for stable and adjustable shooting. Perfect for capturing selfies, group photos, and videos with ease.",
    category: "mobile-accessories",
    price: 19.99,
    discountPercentage: 11.62,
    rating: 2.99,
    stock: 96,
    tags: ["electronics", "camera accessories"],
    brand: "TechGear",
    sku: "RDEQ0W2L",
    weight: 9,
    dimensions: {
      width: 8.42,
      height: 25.12,
      depth: 29.9,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Austin Hudson",
        reviewerEmail: "austin.hudson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Austin Hudson",
        reviewerEmail: "austin.hudson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Gabriel Mitchell",
        reviewerEmail: "gabriel.mitchell@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "2270380444574",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/1.png",
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/2.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/thumbnail.png",
  },
  {
    id: 111,
    title: "Selfie Stick Monopod",
    description:
      "The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo. Compatible with smartphones and cameras.",
    category: "mobile-accessories",
    price: 12.99,
    discountPercentage: 15.29,
    rating: 2.93,
    stock: 33,
    tags: ["electronics", "selfie accessories"],
    brand: "SnapTech",
    sku: "9T6WSF1E",
    weight: 7,
    dimensions: {
      width: 6.11,
      height: 27.92,
      depth: 23.63,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Aaron Cook",
        reviewerEmail: "aaron.cook@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Emma Wilson",
        reviewerEmail: "emma.wilson@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Mia Miller",
        reviewerEmail: "mia.miller@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "2854098561118",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/thumbnail.png",
  },
  {
    id: 112,
    title: "TV Studio Camera Pedestal",
    description:
      "The TV Studio Camera Pedestal is a professional-grade camera support system for smooth and precise camera movements in a studio setting. Ideal for broadcast and production.",
    category: "mobile-accessories",
    price: 499.99,
    discountPercentage: 10.28,
    rating: 4.05,
    stock: 45,
    tags: ["electronics", "camera accessories"],
    brand: "ProVision",
    sku: "8K18CNAH",
    weight: 7,
    dimensions: {
      width: 29.9,
      height: 16.66,
      depth: 13.85,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Mia Miller",
        reviewerEmail: "mia.miller@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Harper Kelly",
        reviewerEmail: "harper.kelly@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Lucas Allen",
        reviewerEmail: "lucas.allen@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "4797157680929",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mobile-accessories/TV%20Studio%20Camera%20Pedestal/1.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/TV%20Studio%20Camera%20Pedestal/thumbnail.png",
  },
  {
    id: 123,
    title: "iPhone 13 Pro",
    description:
      "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
    category: "smartphones",
    price: 1099.99,
    discountPercentage: 18.3,
    rating: 3.42,
    stock: 26,
    tags: ["smartphones", "apple"],
    brand: "Apple",
    sku: "YGQKHPGK",
    weight: 8,
    dimensions: {
      width: 22.39,
      height: 9.77,
      depth: 19.6,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ryan Graham",
        reviewerEmail: "ryan.graham@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Mason Wright",
        reviewerEmail: "mason.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2986724589988",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/thumbnail.png",
  },
  {
    id: 126,
    title: "Oppo F19 Pro Plus",
    description:
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.",
    category: "smartphones",
    price: 399.99,
    discountPercentage: 15.62,
    rating: 2.57,
    stock: 92,
    tags: ["smartphones", "oppo"],
    brand: "Oppo",
    sku: "H2TTGWXB",
    weight: 2,
    dimensions: {
      width: 20.35,
      height: 16.4,
      depth: 13.31,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Lillian Bishop",
        reviewerEmail: "lillian.bishop@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Harper Garcia",
        reviewerEmail: "harper.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "7451360954140",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/thumbnail.png",
  },
  {
    id: 129,
    title: "Realme X",
    description:
      "The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 2.39,
    rating: 4.42,
    stock: 87,
    tags: ["smartphones", "realme"],
    brand: "Realme",
    sku: "5E11C5C4",
    weight: 1,
    dimensions: {
      width: 29.32,
      height: 16.3,
      depth: 24.12,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Emily Johnson",
        reviewerEmail: "emily.johnson@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "0139612574728",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/thumbnail.png",
  },
  {
    id: 130,
    title: "Realme XT",
    description:
      "The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.",
    category: "smartphones",
    price: 349.99,
    discountPercentage: 3.03,
    rating: 4.14,
    stock: 53,
    tags: ["smartphones", "realme"],
    brand: "Realme",
    sku: "GHDMRAP2",
    weight: 4,
    dimensions: {
      width: 28.82,
      height: 23.44,
      depth: 6.21,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Claire Foster",
        reviewerEmail: "claire.foster@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "3985844484131",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/thumbnail.png",
  },
  {
    id: 131,
    title: "Samsung Galaxy S7",
    description:
      "The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 8.83,
    rating: 4.9,
    stock: 55,
    tags: ["smartphones", "samsung galaxy"],
    brand: "Samsung",
    sku: "VZF4Z58Z",
    weight: 8,
    dimensions: {
      width: 23.33,
      height: 27.33,
      depth: 27.02,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Jace Smith",
        reviewerEmail: "jace.smith@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "8841359359362",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/thumbnail.png",
  },
  {
    id: 132,
    title: "Samsung Galaxy S8",
    description:
      "The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology.",
    category: "smartphones",
    price: 499.99,
    discountPercentage: 2.69,
    rating: 3.69,
    stock: 75,
    tags: ["smartphones", "samsung galaxy"],
    brand: "Samsung",
    sku: "GLXQQKBF",
    weight: 6,
    dimensions: {
      width: 6.88,
      height: 8.96,
      depth: 18.13,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Christopher West",
        reviewerEmail: "christopher.west@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Hazel Evans",
        reviewerEmail: "hazel.evans@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "1337599403784",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/thumbnail.png",
  },
  {
    id: 133,
    title: "Samsung Galaxy S10",
    description:
      "The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.",
    category: "smartphones",
    price: 699.99,
    discountPercentage: 0.97,
    rating: 2.81,
    stock: 40,
    tags: ["smartphones", "samsung galaxy"],
    brand: "Samsung",
    sku: "5GJFL98I",
    weight: 3,
    dimensions: {
      width: 28.23,
      height: 7.35,
      depth: 10.68,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Elijah Hill",
        reviewerEmail: "elijah.hill@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "0311929399881",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/thumbnail.png",
  },
  {
    id: 134,
    title: "Vivo S1",
    description:
      "The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.",
    category: "smartphones",
    price: 249.99,
    discountPercentage: 4.25,
    rating: 2.83,
    stock: 13,
    tags: ["smartphones", "vivo"],
    brand: "Vivo",
    sku: "BG6974E7",
    weight: 1,
    dimensions: {
      width: 28.83,
      height: 26.69,
      depth: 23.12,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Alice Smith",
        reviewerEmail: "alice.smith@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Harper Kelly",
        reviewerEmail: "harper.kelly@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Lillian Simmons",
        reviewerEmail: "lillian.simmons@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 3,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "4070349673041",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/thumbnail.png",
  },
  {
    id: 135,
    title: "Vivo V9",
    description:
      "The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design.",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 14.57,
    rating: 3.1,
    stock: 19,
    tags: ["smartphones", "vivo"],
    brand: "Vivo",
    sku: "N9WFE2WH",
    weight: 5,
    dimensions: {
      width: 27.29,
      height: 9.73,
      depth: 14.79,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Elijah Stewart",
        reviewerEmail: "elijah.stewart@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "1506104702332",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/thumbnail.png",
  },
  {
    id: 136,
    title: "Vivo X21",
    description:
      "The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.",
    category: "smartphones",
    price: 499.99,
    discountPercentage: 7.32,
    rating: 2.75,
    stock: 0,
    tags: ["smartphones", "vivo"],
    brand: "Vivo",
    sku: "KSF00BOC",
    weight: 7,
    dimensions: {
      width: 5.72,
      height: 16.47,
      depth: 27.76,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "Out of Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.625Z",
        reviewerName: "Bella Grant",
        reviewerEmail: "bella.grant@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 4,
    meta: {
      createdAt: "2024-05-23T08:56:21.625Z",
      updatedAt: "2024-05-23T08:56:21.625Z",
      barcode: "2543504494043",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/1.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/2.png",
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/thumbnail.png",
  },
];
export default cameras;
