const laptops = [
  {
    id: 78,
    title: "Apple MacBook Pro 14 Inch Space Grey",
    description:
      "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
    category: "laptops",
    price: 1999.99,
    discountPercentage: 9.25,
    rating: 3.13,
    stock: 39,
    tags: ["laptops", "apple"],
    brand: "Apple",
    sku: "QDKO6NRJ",
    weight: 4,
    dimensions: {
      width: 12.38,
      height: 21.55,
      depth: 27.95,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Hunter Gordon",
        reviewerEmail: "hunter.gordon@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Emma Wilson",
        reviewerEmail: "emma.wilson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "David Martinez",
        reviewerEmail: "david.martinez@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.622Z",
      updatedAt: "2024-05-23T08:56:21.622Z",
      barcode: "3883623063065",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png",
  },
  {
    id: 79,
    title: "Asus Zenbook Pro Dual Screen Laptop",
    description:
      "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.",
    category: "laptops",
    price: 1799.99,
    discountPercentage: 9.21,
    rating: 3.14,
    stock: 38,
    tags: ["laptops"],
    brand: "Asus",
    sku: "4A9KFMBG",
    weight: 8,
    dimensions: {
      width: 19.67,
      height: 11.05,
      depth: 14.32,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Ava Harris",
        reviewerEmail: "ava.harris@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Brayden Fleming",
        reviewerEmail: "brayden.fleming@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.622Z",
      updatedAt: "2024-05-23T08:56:21.622Z",
      barcode: "2899455033799",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/thumbnail.png",
  },
  {
    id: 80,
    title: "Huawei Matebook X Pro",
    description:
      "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.",
    category: "laptops",
    price: 1399.99,
    discountPercentage: 15.25,
    rating: 4.62,
    stock: 34,
    tags: ["laptops"],
    brand: "Huawei",
    sku: "U2CBNNB0",
    weight: 9,
    dimensions: {
      width: 22.11,
      height: 11.11,
      depth: 23.07,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Samantha Howard",
        reviewerEmail: "samantha.howard@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2024-05-23T08:56:21.622Z",
        reviewerName: "Brayden Fleming",
        reviewerEmail: "brayden.fleming@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.622Z",
      updatedAt: "2024-05-23T08:56:21.622Z",
      barcode: "1232723732298",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/thumbnail.png",
  },
  {
    id: 81,
    title: "Lenovo Yoga 920",
    description:
      "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.",
    category: "laptops",
    price: 1099.99,
    discountPercentage: 7.77,
    rating: 2.98,
    stock: 71,
    tags: ["laptops"],
    brand: "Lenovo",
    sku: "MST9WZQY",
    weight: 7,
    dimensions: {
      width: 11.02,
      height: 14.45,
      depth: 24.09,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.623Z",
      updatedAt: "2024-05-23T08:56:21.623Z",
      barcode: "9590995785298",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/thumbnail.png",
  },
  {
    id: 82,
    title: "New DELL XPS 13 9300 Laptop",
    description:
      "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.",
    category: "laptops",
    price: 1499.99,
    discountPercentage: 11.7,
    rating: 2.98,
    stock: 18,
    tags: ["laptops"],
    brand: "Dell",
    sku: "XBJJ446X",
    weight: 10,
    dimensions: {
      width: 12.09,
      height: 6.43,
      depth: 15.69,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.623Z",
        reviewerName: "Daniel Taylor",
        reviewerEmail: "daniel.taylor@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.623Z",
      updatedAt: "2024-05-23T08:56:21.623Z",
      barcode: "0358629687929",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/1.png",
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/2.png",
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/thumbnail.png",
  },
];
export default laptops;
