const watches = [
  {
    id: 93,
    title: "Brown Leather Belt Watch",
    description:
      "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    category: "mens-watches",
    price: 89.99,
    discountPercentage: 15.01,
    rating: 4.47,
    stock: 69,
    tags: ["watches", "leather watches"],
    brand: "Fashion Timepieces",
    sku: "WGZ21MSA",
    weight: 10,
    dimensions: {
      width: 18.39,
      height: 10.82,
      depth: 10.52,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Oscar Powers",
        reviewerEmail: "oscar.powers@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Eli Ward",
        reviewerEmail: "eli.ward@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Stella Hughes",
        reviewerEmail: "stella.hughes@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "9559180055872",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Brown%20Leather%20Belt%20Watch/thumbnail.png",
  },
  {
    id: 94,
    title: "Longines Master Collection",
    description:
      "The Longines Master Collection is an elegant and refined watch known for its precision and craftsmanship. With a timeless design, it's a symbol of luxury and sophistication.",
    category: "mens-watches",
    price: 1499.99,
    discountPercentage: 0.64,
    rating: 2.64,
    stock: 65,
    tags: ["watches", "luxury watches"],
    brand: "Longines",
    sku: "LA7B9XEV",
    weight: 2,
    dimensions: {
      width: 5.83,
      height: 12.48,
      depth: 7.65,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Victoria McDonald",
        reviewerEmail: "victoria.mcdonald@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Mia Rodriguez",
        reviewerEmail: "mia.rodriguez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "1865008250672",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png",
  },
  {
    id: 95,
    title: "Rolex Cellini Date Black Dial",
    description:
      "The Rolex Cellini Date with Black Dial is a classic and prestigious watch. With a black dial and date complication, it exudes sophistication and is a symbol of Rolex's heritage.",
    category: "mens-watches",
    price: 8999.99,
    discountPercentage: 14.28,
    rating: 3.61,
    stock: 84,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "J3GPKQW0",
    weight: 6,
    dimensions: {
      width: 12.17,
      height: 27.99,
      depth: 10.36,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Gavin Stanley",
        reviewerEmail: "gavin.stanley@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Stella Hughes",
        reviewerEmail: "stella.hughes@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "8917585155737",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Cellini%20Date%20Black%20Dial/thumbnail.png",
  },
  {
    id: 97,
    title: "Rolex Datejust",
    description:
      "The Rolex Datejust is an iconic and versatile timepiece with a date window. Known for its timeless design and reliability, it's a symbol of Rolex's watchmaking excellence.",
    category: "mens-watches",
    price: 10999.99,
    discountPercentage: 9.69,
    rating: 4.94,
    stock: 11,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "86V20NWJ",
    weight: 5,
    dimensions: {
      width: 9.68,
      height: 7.29,
      depth: 5.67,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Max Russell",
        reviewerEmail: "max.russell@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Jonathan Pierce",
        reviewerEmail: "jonathan.pierce@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Asher Scott",
        reviewerEmail: "asher.scott@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "4957618378388",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Datejust/thumbnail.png",
  },
  {
    id: 98,
    title: "Rolex Submariner Watch",
    description:
      "The Rolex Submariner is a legendary dive watch with a rich history. Known for its durability and water resistance, it's a symbol of adventure and exploration.",
    category: "mens-watches",
    price: 13999.99,
    discountPercentage: 0.82,
    rating: 2.97,
    stock: 35,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "XFGRO0O5",
    weight: 5,
    dimensions: {
      width: 5.22,
      height: 27.59,
      depth: 16.93,
    },
    warrantyInformation: "No warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very dissatisfied!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Emily Brown",
        reviewerEmail: "emily.brown@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Julian James",
        reviewerEmail: "julian.james@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "6567997358364",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Rolex%20Submariner%20Watch/thumbnail.png",
  },
  {
    id: 106,
    title: "Apple Watch Series 4 Gold",
    description:
      "The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display.",
    category: "mobile-accessories",
    price: 349.99,
    discountPercentage: 5.14,
    rating: 4.42,
    stock: 68,
    tags: ["electronics", "smartwatches"],
    brand: "Apple",
    sku: "ZNXPOEPT",
    weight: 6,
    dimensions: {
      width: 8.96,
      height: 28.26,
      depth: 26.46,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Ellie Stewart",
        reviewerEmail: "ellie.stewart@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Grayson Coleman",
        reviewerEmail: "grayson.coleman@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.624Z",
        reviewerName: "Alice Smith",
        reviewerEmail: "alice.smith@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.624Z",
      updatedAt: "2024-05-23T08:56:21.624Z",
      barcode: "4492482209885",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/1.png",
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/2.png",
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20Watch%20Series%204%20Gold/thumbnail.png",
  },
  {
    id: 190,
    title: "IWC Ingenieur Automatic Steel",
    description:
      "The IWC Ingenieur Automatic Steel watch is a durable and sophisticated timepiece. With a stainless steel case and automatic movement, it combines precision and style for watch enthusiasts.",
    category: "womens-watches",
    price: 4999.99,
    discountPercentage: 5.76,
    rating: 2.58,
    stock: 85,
    tags: ["watches", "luxury watches"],
    brand: "IWC",
    sku: "OJF7AK1J",
    weight: 4,
    dimensions: {
      width: 12.27,
      height: 5.91,
      depth: 8.71,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very unhappy with my purchase!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "3417342002384",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/IWC%20Ingenieur%20Automatic%20Steel/thumbnail.png",
  },
  {
    id: 191,
    title: "Rolex Cellini Moonphase",
    description:
      "The Rolex Cellini Moonphase watch is a masterpiece of horology. Featuring a moon phase complication, it showcases the craftsmanship and elegance that Rolex is renowned for.",
    category: "womens-watches",
    price: 15999.99,
    discountPercentage: 18.76,
    rating: 3.41,
    stock: 66,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "E8CYFYQL",
    weight: 5,
    dimensions: {
      width: 22.54,
      height: 20.15,
      depth: 25.37,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Would not recommend!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Leah Henderson",
        reviewerEmail: "leah.henderson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very pleased!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Mateo Nguyen",
        reviewerEmail: "mateo.nguyen@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "3517608890772",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png",
  },
  {
    id: 192,
    title: "Rolex Datejust Women",
    description:
      "The Rolex Datejust Women's watch is an iconic timepiece designed for women. With a timeless design and a date complication, it offers both elegance and functionality.",
    category: "womens-watches",
    price: 10999.99,
    discountPercentage: 17.72,
    rating: 3.53,
    stock: 31,
    tags: ["watches", "luxury watches", "women's watches"],
    brand: "Rolex",
    sku: "VKQ2UNB9",
    weight: 8,
    dimensions: {
      width: 14.53,
      height: 29.73,
      depth: 10.22,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very disappointed!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Evan Reed",
        reviewerEmail: "evan.reed@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Isabella Jackson",
        reviewerEmail: "isabella.jackson@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "6032534220602",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Datejust%20Women/thumbnail.png",
  },
  {
    id: 193,
    title: "Watch Gold for Women",
    description:
      "The Gold Women's Watch is a stunning accessory that combines luxury and style. Featuring a gold-plated case and a chic design, it adds a touch of glamour to any outfit.",
    category: "womens-watches",
    price: 799.99,
    discountPercentage: 6.37,
    rating: 3.03,
    stock: 94,
    tags: ["watches", "women's watches"],
    brand: "Fashion Gold",
    sku: "N6I9YEWM",
    weight: 8,
    dimensions: {
      width: 5.9,
      height: 13.64,
      depth: 23.65,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Not as described!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Lucas Allen",
        reviewerEmail: "lucas.allen@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Bella Gonzalez",
        reviewerEmail: "bella.gonzalez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Michael Johnson",
        reviewerEmail: "michael.johnson@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "0793324106392",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/thumbnail.png",
  },
  {
    id: 194,
    title: "Women's Wrist Watch",
    description:
      "The Women's Wrist Watch is a versatile and fashionable timepiece for everyday wear. With a comfortable strap and a simple yet elegant design, it complements various styles.",
    category: "womens-watches",
    price: 129.99,
    discountPercentage: 17.34,
    rating: 2.93,
    stock: 55,
    tags: ["watches", "women's watches"],
    brand: "Fashion Co.",
    sku: "36T6X4M3",
    weight: 8,
    dimensions: {
      width: 24.74,
      height: 25.89,
      depth: 8.18,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Emily Brown",
        reviewerEmail: "emily.brown@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2024-05-23T08:56:21.628Z",
        reviewerName: "Mila Hernandez",
        reviewerEmail: "mila.hernandez@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2024-05-23T08:56:21.628Z",
      updatedAt: "2024-05-23T08:56:21.628Z",
      barcode: "7588684177028",
      qrCode: "https://assets.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/1.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/2.png",
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/3.png",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Women's%20Wrist%20Watch/thumbnail.png",
  },
];
export default watches;
